name: awesome_list_flutterweb_ui
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.6-dev.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bird_flutter: 0.0.2+1
  bird: 0.0.2+1
  timeago: ^2.0.22

dev_dependencies:
  flutter_test:
    sdk: flutter
  extra_pedantic: ^1.1.1+3

flutter:
  uses-material-design: true
