import 'package:awesome_list/model/model.dart';
import 'package:bird/bird.dart';

Map<String, List<EntryData>> allData = {
  "drawers": [
    const EntryData(
      title: "Hidden Drawer Menu",
      description: "Beautiful drawer mode menu feature with perspective animations by Rafael Almeida Barbosa.",
      link: "https://github.com/RafaelBarbosatec/hidden_drawer_menu",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Flutter Inner Drawer",
      description: "Easy way to create an internal drawer (left / right) where you can enter a list-menu or other by Di Natale Antonino.",
      link: "https://github.com/Dn-a/flutter_inner_drawer",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "bottom_bars": [
    const EntryData(
      title: "Fancy Bottom Navigation",
      description: "Animated bottom navigation by Tony Owen.",
      link: "https://github.com/tunitowen/fancy_bottom_navigation",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Circular Bottom Navigation",
      description: "Beautiful animated bottom navigation bar by Iman Khoshabi.",
      link: "https://github.com/imaNNeoFighT/circular_bottom_navigation",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Bottom Navy Bar",
      description: "Beautiful and colorful animated bottom navigation bar by Pedro Massango.",
      link: "https://github.com/pedromassango/bottom_navy_bar",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "sliders": [
    const EntryData(
      title: "RangeSlider",
      description: "2-thumb configurable RangeSlider by Didier Boelens.",
      link: "https://github.com/boeledi/RangeSlider",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Fluid Slider",
      description: "A slider with a minimal design and fluid like animation by Vamsi Krishna.",
      link: "https://github.com/rvamsikrishna/flutter_fluid_slider",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Flutter Xlider",
      description: "A material design slider and range slider, horizontal and vertical, with RTL support by Ali-Azmoud.",
      link: "https://github.com/Ali-Azmoud/flutter_xlider",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "lists": [
    const EntryData(
      title: "Sticky Infinite List",
      description: "Highly configurable multi directional infinite list with Sticky Headers by TatsuUkraine.",
      link: "https://github.com/TatsuUkraine/flutter_sticky_infinite_list",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Sticky Header",
      description: "Sliver based sticky headers by Romain Rastel.",
      link: "https://github.com/letsar/flutter_sticky_header",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Sticky Headers",
      description: "Sticky Header",
      link: "https://github.com/slightfoot/flutter_sticky_headers",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Reorderables",
      description: "Drag&Drop Table, Row, Column, Wrap(Grid) and SliverList elements by Hansheng Chiu.",
      link: "https://github.com/hanshengchiu/reorderables",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Liquid Pull To Refresh",
      description: "A beautiful and custom refresh indicator by Ayush Agarwal.",
      link: "https://github.com/aagarwal1012/Liquid-Pull-To-Refresh",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Infinite Listview",
      description: "Infinite scroll in both directions by Simon Lightfoot.",
      link: "https://github.com/fluttercommunity/flutter_infinite_listview",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Scroll To Index",
      description: "Scroll to specified child element with given index for SliverList/ListView by Jerry Chen.",
      link: "https://github.com/quire-io/scroll-to-index",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "In View Notifier List",
      description: "ListView that notify when widgets are on screen within a provided area by Vamsi Krishna.",
      link: "https://github.com/rvamsikrishna/inview_notifier_list",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Drag Select GridView",
      description: "GridView that supports both dragging and tapping to select its items by Hugo Passos.",
      link: "https://github.com/hugocbpassos/drag_select_grid_view",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "effect": [
    const EntryData(
      title: "Frosted Glass",
      description: "Render effect by Collin Jackson.",
      link: "http://stackoverflow.com/questions/43550853/how-do-i-do-the-frosted-glass-effect-in-flutter",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Parallax",
      description: "ViewPager by Iiro Krankka.",
      link: "https://github.com/FlutterRocks/page-transformer",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Shimmer",
      description: "Shimmer effect while content is loading by HungHD.",
      link: "https://github.com/hnvn/flutter_shimmer",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Wave",
      description: "Displaying some waves with custom color, duration, floating and blur effects by RockerFlower.",
      link: "https://github.com/i-protoss/wave",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Liquid Swipe",
      description: "Liquid swipe to your stacked containers by Sahdeep Singh.",
      link: "https://github.com/iamSahdeep/liquid_swipe_flutter",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "PhotoFilters",
      description: "Apply filters to an image by Sharafudheen KK.",
      link: "https://github.com/skkallayath/photofilters",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "calendar": [
    const EntryData(
      title: "Calendar Widget",
      description: "Calendar widget by David Bennett.",
      link: "https://github.com/pinkfish/flutter_calendar",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Calendar Carousel Widget",
      description: "Calendar carousel by dooboolab",
      link: "https://github.com/dooboolab/flutter_calendar_carousel",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Date range picker",
      description: "Date range picker modified based on Flutter date picker by An Doan",
      link: "https://github.com/anicdh/date_range_picker",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Table Calendar",
      description: "Calendar organized neatly into a Table, with vertical autosizing by Aleksander Woźniak.",
      link: "https://github.com/aleksanderwozniak/table_calendar",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "image": [
    const EntryData(
      title: "Image Picker",
      description: "Images Selection by Collin Jackson.",
      link: "https://github.com/flutter/plugins/tree/master/packages/image_picker",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Carousel Slider",
      description: "Carousel slider widget, support infinite scroll and custom child widget by serenader.",
      link: "https://github.com/serenader2014/flutter_carousel_slider",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Parallax Image",
      description: "Image parallax by Anatoly Pulyaevskiy.",
      link: "https://github.com/pulyaevskiy/parallax-image",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Photo View",
      description: "Scalable image view with loading placeholder by Renan C. Araújo.",
      link: "https://github.com/renancaraujo/photo_view",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "SVG",
      description: "SVG parsing, rendering, and widget library by Dan Field.",
      link: "https://github.com/dnfield/flutter_svg",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Image Cropper",
      description: "Crop your images support ratio, rotation, zoom by HungHD.",
      link: "https://github.com/hnvn/flutter_image_cropper",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Cached Network Image",
      description: "Show images from the internet and keep them in the cache directory by.",
      link: "https://github.com/renefloor/flutter_cached_network_image",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Multi Image Picker",
      description: "Display multi image picker by Radoslav Vitanov.",
      link: "https://github.com/Sh1d0w/multi_image_picker",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Lottie",
      description: "Use airbnb's popular After Effects Animation library by Cameron Smith.",
      link: "https://github.com/CameronStuartSmith/flutter_lottie",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Bitmap",
      description: "Perform Bitmap manipulations (such as contrast and exposure) with a help from the Dart FFI by Renan C. Araújo.",
      link: "https://github.com/renancaraujo/bitmap",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "map": [
    const EntryData(
      title: "Google Map View",
      description: "Displaying google map plugin by AppTree Software.",
      link: "https://github.com/apptreesoftware/flutter_google_map_view",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "GeoCoder",
      description: "Forward and reverse geocoding by Aloïs Deniel.",
      link: "https://github.com/aloisdeniel/flutter_geocoder",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Map",
      description: "Solution based on Leaflet and customizable by AppTree Software.",
      link: "https://github.com/apptreesoftware/flutter_map",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Mapbox GL",
      description: "Interactive, customizable vector maps by Mapbox.",
      link: "https://github.com/mapbox/flutter-mapbox-gl",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "AMap",
      description: "Access to AMap services(高德地图) by OpenFlutter.",
      link: "https://github.com/OpenFlutter/amap_base_flutter",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "charts": [
    const EntryData(
      title: "Circular Chart",
      description: "Animated radial and pie charts by Victor Choueiri.",
      link: "https://github.com/xqwzts/flutter_circular_chart",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Charts",
      description: "LineChart and VerticalBarChart Library by Milan Zimmermann.",
      link: "https://github.com/mzimmerm/flutter_charts",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Sparkline",
      description: "Sparkline by Victor Choueiri.",
      link: "https://github.com/xqwzts/flutter_sparkline",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Charts",
      description: "By Google Charts Team.",
      link: "https://github.com/google/charts",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Flutter Plot",
      description: "Pretty plots by R. C. Howell.",
      link: "https://github.com/RCHowell/flutter_plot",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Candlesticks",
      description: "OHLC and Trade Volume Charts by Trent Piercy.",
      link: "https://github.com/trentpiercy/flutter-candlesticks",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "FCharts",
      description: "Beautiful, responsive, animated charts by Keenan Thompson.",
      link: "https://github.com/thekeenant/fcharts",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "FL Chart",
      description: "Draw fantastic charts in Flutter by Iman Khoshabi.",
      link: "https://github.com/imaNNeoFighT/fl_chart",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Bezier Chart",
      description: "Beautiful bezier line chart widget for flutter that is highly interactive and configurable by Diego Velasquez.",
      link: "https://github.com/aeyrium/bezier-chart",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "navigation": [
    const EntryData(
      title: "Fluro",
      description: "The brightest, hippest, coolest router for Flutter with Navigation, wildcard, query, transitions by Posse.",
      link: "https://github.com/goposse/fluro",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "PageView Indicator",
      description: "Build page indicators for the PageView by Leo Cavalcante.",
      link: "https://github.com/leocavalcante/page_view_indicator",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Swiper",
      description: "Horizontal, Vertical, Partial swipe with indicator by Xueliang Ren.",
      link: "https://github.com/jzoom/flutter_swiper",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "text": [
    const EntryData(
      title: "Markdown",
      description: "Markdown renderer for Flutter. It supports the original format, but no inline html.",
      link: "https://github.com/flutter/flutter_markdown",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Masked Text",
      description: "Masked text with custom and monetary formatting by Ben-hur Santos Ott.",
      link: "https://github.com/benhurott/flutter-masked-text",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Zefyr",
      description: "Soft and gentle rich text editing by Memspace.",
      link: "https://github.com/memspace/zefyr",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "AutoSizeText",
      description: "Automatically resizes text to fit perfectly within its bounds by Simon Leier.",
      link: "https://github.com/leisim/auto_size_text",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Parsed Text",
      description: "Interactive text based on content recognition, also supports Regex by Fayeed Pawaskar.",
      link: "https://github.com/fayeed/flutter_parsed_text",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "auth": [
    const EntryData(
      title: "Local Auth",
      description: "Touch ID, lock code, fingerprint auth on iOS and Android.",
      link: "https://github.com/flutter/plugins/tree/master/packages/local_auth",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Login",
      description: "FaceID, TouchID, and Fingerprint Reader by Rody Davis.",
      link: "https://github.com/AppleEducate/flutter_login",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Google Sign-In",
      description: "Google OAuth.",
      link: "https://github.com/flutter/plugins/tree/master/packages/google_sign_in",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Firebase Auth",
      description: "Firebase OAuth.",
      link: "https://github.com/flutter/plugins/tree/master/packages/firebase_auth",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Facebook Login",
      description: "Authenticate with native Android & iOS Facebook login SDKs by Iiro Krankka.",
      link: "https://github.com/roughike/flutter_facebook_login",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Apple Sign-In",
      description: "Apple sign in by Tom Gilder.",
      link: "https://github.com/tomgilder/flutter_apple_sign_in",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "OAuth",
      description: "Buffer, Strava, Unsplash, Github OAuth by Joe Birch.",
      link: "https://github.com/hitherejoe/FlutterOAuth",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Firebase Phone Auth",
      description: "Phone number auth via SMS by Gildásio Filho.",
      link: "https://medium.com/@gildaswise/flutter-adding-sign-in-with-google-and-phone-authentication-to-your-app-69f681518f9b",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "SimpleAuth",
      description: "Azure Active Directory, Amazon, Dropbox, Facebook, Github, Google, Instagram, Linked In, Microsoft Live Connect, Github, OAuth, Basic Auth by James Clancey.",
      link: "https://github.com/Clancey/simple_auth",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Flutter AppAuth",
      description: "Plugin that provides a wrapper around the AppAuth iOS and Android SDKs by Michael Bui.",
      link: "https://github.com/MaikuB/flutter_appauth",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "analytics": [
    const EntryData(
      title: "Usage",
      description: "Google Analytics wrapper for command-line, web, and Flutter apps.",
      link: "https://github.com/dart-lang/usage",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Firebase Analytics",
      description: "Connect to Firebase Analytics API.",
      link: "https://github.com/flutter/plugins/tree/master/packages/firebase_analytics",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Segment.com Analytics",
      description: "Make your Segment.com analytics a breeze! by Faisal Abid.",
      link: "https://github.com/FaisalAbid/segment-analytics-flutter",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Pure Mixpanel",
      description: "Analytics for the popular Mixpanel.com Nick Manning.",
      link: "https://github.com/seenickcode/pure_mixpanel",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "i18n": [
    const EntryData(
      title: "Flutter Translate",
      description: "Internationalization (i18n) library by Florin Bratan.",
      link: "https://github.com/bratan/flutter_translate",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "GenLang",
      description: "Code generator for Internationalization by King Wu.",
      link: "https://github.com/KingWu/gen_lang",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "dl_md": [
    const EntryData(
      title: "Material Color Picker",
      description: "Based on the Google Docs color picker by Lung Razvan.",
      link: "https://github.com/long1eu/material_color_picker",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Unicorn Speed Dial",
      description: "Floating Action Button with Speed Dial by Tiago Martins.",
      link: "https://github.com/tiagojencmartins/unicornspeeddial",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Slidable",
      description: "Slidable list item with left and right slide actions by Romain Rastel.",
      link: "https://github.com/letsar/flutter_slidable",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "dl_cupertino": [
    const EntryData(
      title: "Peek & Pop",
      description: "Peek & Pop implementation based on the iOS functionality by Ali Yigit Bireroglu.",
      link: "https://github.com/aliyigitbireroglu/flutter-peek-and-pop",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "dl_eva": [
    const EntryData(
      title: "eva_icons_flutter",
      description: "Flutter package for Eva Icons. Eva Icons is a pack of more than 480 beautifully crafted Open Source icons for common actions and items.",
      link: "https://pub.dev/packages/eva_icons_flutter",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "equinox",
      description: "Flutter UI library based on Eva Design System ✨",
      link: "https://github.com/kekland/equinox",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "audio": [
    const EntryData(
      title: "Flutter Audio Recorder",
      description: "Provides full controls and access to recording details such as level metering by Wenyan Li.",
      link: "https://github.com/shadow-app/flutter_audio_recorder",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Audio Recorder",
      description: "Record audio and store it locally by Jordan Alcaraz.",
      link: "https://github.com/ZaraclaJ/audio_recorder",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Stereo",
      description: "Playing music on iOS and Android by 2Find.",
      link: "https://github.com/2find/stereo",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Flutter Sound",
      description: "Flutter audio recorder and player at one hand by dooboolab.",
      link: "https://github.com/dooboolab/flutter_sound",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "video": [
    const EntryData(
      title: "WebRTC",
      description: "WebRTC plugin for iOS/Android by CloudWebRtc.",
      link: "https://github.com/cloudwebrtc/flutter-webrtc",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Chewie",
      description: "Provides low-level access to video playback by Brian Egan.",
      link: "https://github.com/brianegan/chewie",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "voice": [
    const EntryData(
      title: "Speech Recognition",
      description: "Speech to text by Erick Ghaumez.",
      link: "https://github.com/rxlabz/speech_recognition",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "animation": [
    const EntryData(
      title: "Sequence Animation",
      description: "Composite staggered animations by Norbert Kozsir.",
      link: "https://github.com/Norbert515/flutter_sequence_animation",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "SpinKit",
      description: "Animated loading indicators by Jeremiah Ogbomo.",
      link: "https://github.com/jogboms/flutter_spinkit",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Villains",
      description: "Page transition animations by Norbert Kozsir.",
      link: "https://github.com/Norbert515/flutter_villains",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "AnimatedTextKit",
      description: "A collection of cool text animations by Ayush Agarwal.",
      link: "https://github.com/aagarwal1012/Animated-Text-Kit",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Drawing Animation",
      description: "Create drawing line animations based on SVG path data by Carl Hauck.",
      link: "https://github.com/biocarl/drawing_animation",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Simple Animations",
      description: "Create awesome custom animations easily by Felix Blaschke.",
      link: "https://github.com/felixblaschke/simple_animations",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Flutter-animation-set",
      description: "Easy to build an animation set by efoxTeam.",
      link: "https://github.com/efoxTeam/flutter-animation-set",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Staggered Animations",
      description: "Easily add staggered animations to your ListView, GridView, Column and Row by mobiten.",
      link: "https://github.com/mobiten/flutter_staggered_animations",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "game_engine": [
    const EntryData(
      title: "Flame",
      description: "Minimalist game engine by Luan Nico.",
      link: "https://github.com/luanpotter/flame",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "SpriteWidget",
      description: "Toolkit for building complex, high performance animations and 2D games by Viktor Lidholt.",
      link: "https://github.com/spritewidget/spritewidget",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "math": [
    const EntryData(
      title: "trotter",
      description: "Class definitions for pseudo-lists that simplify working with structures commonly encountered in combinatorics such as permutations, combinations and subsets.",
      link: "https://pub.dev/packages/trotter",
      pubdevPackageNameForBadge: Some("trotter"),
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "extended_math",
      description: "Library that adds functionality of all maths sections that don't exist in dart:math.",
      link: "https://pub.dev/packages/extended_math",
      pubdevPackageNameForBadge: Some("extended_math"),
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "state_management": [
    const EntryData(
      title: "provider",
      description: "A mixture between dependency injection and state management, built with widgets for widgets.",
      link: "https://pub.dev/packages/provider",
      pubdevPackageNameForBadge: Some("provider"),
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "bloc",
      description: "A predictable state management library that helps implement the BLoC (Business Logic Component) design pattern.",
      link: "https://pub.dev/packages/flutter_bloc",
      pubdevPackageNameForBadge: Some("flutter_bloc"),
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "flutter_bloc",
      description: "Flutter Widgets that make it easy to implement the BLoC (Business Logic Component) design pattern. Built to be used with the bloc state management package.",
      link: "https://pub.dev/packages/flutter_bloc",
      pubdevPackageNameForBadge: Some("flutter_bloc"),
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "redux",
      description: "Redux for Dart",
      link: "https://pub.dev/packages/redux",
      pubdevPackageNameForBadge: Some("redux"),
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "mobx",
      description: "MobX is a library for reactively managing the state of your applications. Use the power of observables, actions, and reactions to supercharge your Dart and Flutter apps.",
      link: "https://pub.dev/packages/mobx",
      pubdevPackageNameForBadge: Some("mobx"),
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Flux",
      description: "Implementation of the Flux framework by Google.",
      link: "https://github.com/google/flutter_flux",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "fp": [
    const EntryData(
      title: "dartz",
      description: "Functional Programming in Dart. Purify your Dart code using efficient immutable data structures, monads, lenses and other FP tools.",
      link: "https://pub.dev/packages/dartz",
      pubdevPackageNameForBadge: Some("dartz"),
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "functional_data",
      description: "Annotations and helpers for lenses for code generated with the `function_data_generator` package.",
      link: "https://pub.dev/packages/functional_data",
      pubdevPackageNameForBadge: Some("functional_data"),
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Hooks",
      description: "Advanced code sharing between widgets by Remi Rousselet.",
      link: "https://github.com/rrousselGit/flutter_hooks",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Functional widget",
      description: "Code generator writing widgets as functions with annotations by Remi Rousselet.",
      link: "https://github.com/rrousselGit/functional_widget",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "abstract_dart",
      description: "A collection of algebraic structures borrowed from abstract algebra. Semigroup, Monoid, Group & Field.",
      link: "https://pub.dev/packages/abstract_dart",
      pubdevPackageNameForBadge: Some("abstract_dart"),
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "social_apps": [
    const EntryData(
      title: "Meme Chat",
      description: "Chat app on Flutter, using Firebase, Google Sign In, and device camera integration by a team of Googlers.",
      link: "https://github.com/efortuna/memechat",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Flitter",
      description: "Glitter app by Hadrien Lejard and Kevin Segaud. It uses Redux and Jaguar.",
      link: "https://github.com/dart-flitter/flitter",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Lime",
      description: "Lime social network by Sebastian Sellmair.",
      link: "https://github.com/fablue/lime-flutter",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "FlutterGram",
      description: "Complete Instagram based on Firestore & Google Functions by MDanics.",
      link: "https://github.com/mdanics/fluttergram",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Instory",
      description: "Instagram story downloader with a beautiful UI Sarath.",
      link: "https://github.com/InvertedX/instory",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Enigma",
      description: "Privacy chat with end-to-end encryption by AmitJoki.",
      link: "https://github.com/AmitJoki/Enigma",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Timy Messenger",
      description: "Group messaging app with a focus on organizing events by Miguel Beltran and Franz Heinfling.",
      link: "https://github.com/janoodleFTW/timy-messenger",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "multimedia_apps": [
    const EntryData(
      title: "History Of Everything",
      description: "Animated vertical timeline of humanity by 2D, Inc.",
      link: "https://github.com/2d-inc/HistoryOfEverything",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Planets",
      description: "Planet exploration that demonstrate rich UI by Sergi Martínez.",
      link: "https://github.com/sergiandreplace/flutter_planets_tutorial",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "NewsBuzz",
      description: "Firebase backed news reader using News API by Ankur Kedia.",
      link: "https://github.com/theankurkedia/NewsBuzz",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Music Player",
      description: "Full featured music player by Pawan Kumar.",
      link: "https://github.com/iampawan/Flutter-Music-Player",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Cinematic",
      description: "UI for Movie DB Public API by Aaron Oertel.",
      link: "https://github.com/aaronoe/FlutterCinematic",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Chillify",
      description: "Fancy music app made with Provider and Bloc pattern by Karim Elghamry.",
      link: "https://github.com/KarimElghamry/chillify",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "widget_showcase": [
    const EntryData(
      title: "Flutter Team Samples",
      description: "Collection of examples (including maps, json, Material and Cupertino) by the Flutter team.",
      link: "https://github.com/flutter/samples",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Flutter Common Widgets",
      description: "Collection of official widgets demos & docs in chinese to help developers learn quickly by Alibaba Auction Frontend Team.",
      link: "https://github.com/alibaba/flutter-common-widgets-app",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Reply",
      description: "'Reply' Material Design case study by Frederik Schweiger.",
      link: "https://github.com/flschweiger/reply",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "os_templates": [
    const EntryData(
      title: "Movie Details",
      description: "Movie details page by Iiro Krankka.",
      link: "https://github.com/FlutterRocks/movie-details-ui",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Mates",
      description: "How to load profiles from the randomuser.me API and a nice profile details page by Iiro Krankka.",
      link: "https://github.com/CodemateLtd/FlutterMates",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Weather",
      description: "Weather app to learn how to use Canvas and Animation by Alessandro Aime",
      link: "https://github.com/alessandroaime/Weather",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "TodoMVC",
      description: "TODO application ready to go with different flavors : Vanilla, Redux, built_redux by Brian Egan.",
      link: "https://github.com/brianegan/flutter_architecture_samples",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Restaurant Menu",
      description: "Restaurant menu by Braulio Cassule.",
      link: "https://github.com/braulio94/menu_flutter",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "UI Challenges",
      description: "Profile, Travel, Food App by Tomi Alagbe.",
      link: "https://github.com/tomialagbe/flutter_ui_challenges",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Cupertino Settings",
      description: "iOS Settings by Matthias Rupp.",
      link: "https://github.com/matthinc/flutter_cupertino_settings",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Music Player",
      description: "music player component by Tobe O.",
      link: "https://github.com/thosakwe/flutter_music_player",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Dashboard",
      description: "Dashboard and Shop Items by Ivascu Adrian.",
      link: "https://github.com/Ivaskuu/dashboard",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Todo",
      description: "Todo template from Dribble by Marc L.",
      link: "https://github.com/littlemarc2011/FlutterTodo",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Card Swipe Animation",
      description: "Swipe cards template by Ruchika Gupta.",
      link: "https://github.com/geekruchika/FlutterCardSwipe",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "UI Kit",
      description: "Collection of useful UIs in a UIKit by Pawan Kumar.",
      link: "https://github.com/iampawan/Flutter-UI-Kit",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Book",
      description: "Bookshelf by Ardiansyah Putra.",
      link: "https://github.com/putraxor/flutter-book-app",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "The Gorgeous Login",
      description: "Design and smooth login template by Hugo Extrat.",
      link: "https://github.com/huextrat/TheGorgeousLogin",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Liquid Pay Payment App",
      description: "Liquid Pay App Concept by Long Hoang.",
      link: "https://github.com/longhoang2984/flutter_payment_app_ui",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "DrawApp",
      description: "Sample Drawing App to demonstrate how to allow user to draw onto canvas with color picker and brush thickness slider by Jake Gough.",
      link: "https://github.com/SnakeyHips/drawapp",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Starter Kit",
      description: "App Store implementation to learn Bloc, RxDart, Sqflite, Fluro and Dio. by King Wu.",
      link: "https://github.com/KingWu/flutter_starter_kit",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Feather",
      description: "Beautiful weather application. Application includes RxDart, Dio, BLoC, i18n, unit and widget tests. by Jakub Homlala.",
      link: "https://github.com/jhomlala/feather",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Clone UI Challenges",
      description: "Collection of useful UIs clones by Javier González.",
      link: "https://github.com/javico2609/flutter-challenges",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "FlutterFoodybite",
      description: "A beautiful food app UI template by JideGuru.",
      link: "https://github.com/JideGuru/FlutterFoodybite",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "other_apps": [
    const EntryData(
      title: "DroidKaigi2018-flutter",
      description: "Unofficial conference app for DroidKaigi 2018 Tokyo by konifar.",
      link: "https://github.com/konifar/droidkaigi2018-flutter",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "WhatTodo",
      description: "Todoist like UI by Burhanuddin Rashid.",
      link: "https://github.com/burhanrashid52/WhatTodo",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "BookSearch",
      description: "Digital BookShelf for your reading progress by Norbert515.",
      link: "https://github.com/Norbert515/BookSearch",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Beer-Me-Up",
      description: "Beer tracking nicely designed by Benoit Letondor.",
      link: "https://github.com/benoitletondor/Beer-Me-Up",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Trace",
      description: "Modern and powerful crypto portfolio & market explorer by Trent Piercy",
      link: "https://github.com/trentpiercy/trace",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Taskist",
      description: "Taskist is a ToDo List app for Task Management by Hugo EXTRAT.",
      link: "https://github.com/huextrat/Taskist",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Tourism",
      description: "Tourism app based on redux w/ animations & i18n by blueMix.",
      link: "https://github.com/bluemix/tourism-demo",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Trinity Orientation @ Univ Toronto",
      description: "Orientation week at Trinity College, U of T by Matthew Tory.",
      link: "https://github.com/matthewtory/trinity-orientation-2018",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Transform Widget",
      description: "Image widgets as 3D game engine sprites by Paul Thomas.",
      link: "https://github.com/DrPaulT/flutter-engine-test",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Deer",
      description: "Minimalist Todo Planner built using BLoC pattern by Aleksander Woźniak.",
      link: "https://github.com/aleksanderwozniak/deer",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "TailorMade",
      description: "Managing a Fashion designer's daily routine using a mixture of ReBLoC w/ Firebase Cloud Store & Functions by Jeremiah Ogbomo.",
      link: "https://github.com/jogboms/tailor_made",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Spacex-Go",
      description: "Simple yet powerful, open-source SpaceX launch tracker. jesusrp98.",
      link: "https://github.com/jesusrp98/spacex-go",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Superhero Interaction",
      description: "Cool Superhero interaction animation by Pinkesh Darji.",
      link: "https://github.com/pinkeshdarji/SuperHeroInteraction",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Pokedex",
      description: "Pokedex app with beautiful UI and smooth animation by Hung Pham.",
      link: "https://github.com/scitbiz/flutter_pokedex",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "games": [
    const EntryData(
      title: "Developer Quest",
      description: "Become a tech lead, slay bugs by 2D, Inc.",
      link: "https://github.com/2d-inc/developer_quest",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Flip",
      description: "Reversi game by Andrew Brogdon.",
      link: "https://github.com/RedBrogdon/flutterflip",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "2048",
      description: "2048 game by Anuran Barman.",
      link: "https://github.com/anuranBarman/2048",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "TRex",
      description: "Port of the famous Chrome's Trex game by Renan C. Araújo.",
      link: "https://github.com/renancaraujo/trex-flame",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Crush",
      description: "How to build a Math-3 game, like Candy Crush, Bejeweled by Didier Boelens.",
      link: "https://github.com/boeledi/flutter_crush",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Slide Puzzle",
      description: "Classic slide (15) puzzle by Kevin Moore.",
      link: "https://github.com/kevmoo/slide_puzzle",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Tetris",
      description: "Tetris game by YangBin.",
      link: "https://github.com/boyan01/flutter-tetris",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "community_communication": [
    const EntryData(
      title: "Gitter",
      description: "Exchange channel.",
      link: "https://gitter.im/flutter/flutter",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Discord",
      description: "Discord server to discuss and get help by Pritykin.",
      link: "https://discord.gg/N7Yshp4",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "community_news": [
    const EntryData(
      title: "r/FlutterDev",
      description: "Official Reddit community about Flutter",
      link: "https://www.reddit.com/r/FlutterDev/",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "r/Flutter",
      description: "Reddit community about Flutter",
      link: "https://www.reddit.com/r/Flutter/",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "r/dartlang",
      description: "Reddit community about Dart",
      link: "https://www.reddit.com/search/?q=r%2Fdartlang",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Hashnode",
      description: "Read and write posts, participate in discussions or ask questions.",
      link: "https://hashnode.com/n/flutter",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "community_other": [
    const EntryData(
      title: "Flutter Community on GitHub",
      description: "Central place for community made packages.",
      link: "https://discord.gg/https://github.com/fluttercommunity",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Flutter Events",
      description: "An open list of Flutter events by @hillelcoren.",
      link: "https://flutterevents.com/",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "FlutterX",
      description: "Searchable list of resources by Hillel Coren.",
      link: "https://flutterx.com/",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "education_advanced": [
    const EntryData(
      title: "Rendering Pipeline",
      description: "Engine architecture by Adam Barth.",
      link: "https://www.youtube.com/watch?v=UUfXWzp0-DU",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Render Objects",
      description: "What are Widgets, RenderObjects and Elements? by Norbert515.",
      link: "https://medium.com/flutter-community/flutter-what-are-widgets-renderobjects-and-elements-630a57d05208",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Streams and RxDart",
      description: "Skillmatters presentation by Brian Egan.",
      link: "https://skillsmatter.com/skillscasts/12254-flutter-with-streams-and-rxdart",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Gesture System",
      description: "Flutter Deep Dive: Gestures by Nash.",
      link: "https://medium.com/flutter-community/flutter-deep-dive-gestures-c16203b3434f",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Schemas",
      description: "Widget, State, Context and InheritedWidget explanations by Didier Boelens.",
      link: "https://www.didierboelens.com/2018/06/widget---state---context---inheritedwidget/",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Rendering Engine Tutorial",
      description: "Flutter's Rendering Engine: A Tutorial by AbdulRahman AlHamali.",
      link: "https://medium.com/saugo360/flutters-rendering-engine-a-tutorial-part-1-e9eff68b825d",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Inherited Widget",
      description: "Flutter’s InheritedWidget to hold app state by Chema Molins.",
      link: "https://medium.com/@chemamolins/is-flutters-inheritedwidget-a-good-fit-to-hold-app-state-2ec5b33d023e",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "From Mobile to Desktop",
      description: "Building applications for smartphones and desktops by Marcelo Henrique Neppel.",
      link: "https://medium.com/flutter-community/flutter-from-mobile-to-desktop-93635e8de64e",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Accessibility Widgets",
      description: "Deep dive information about all aspects of accessibility by Muhammed Salih Güler.",
      link: "https://medium.com/flutter-community/a-deep-dive-into-flutters-accessibility-widgets-eb0ef9455bc",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Profiling w/ Timeline",
      description: "Using the Timeline allows you to find and address specific performance issues in your application by Chinmay Garde.",
      link: "https://medium.com/flutter-io/profiling-flutter-applications-using-the-timeline-a1a434964af3",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Parallax Effect",
      description: "Parallax & non linear animation by Marcin Szalek.",
      link: "https://marcinszalek.pl/flutter/tickets-challenge-parallax",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Build Flavor",
      description: "Define build configurations and switch them by Salvatore Giordano.",
      link: "https://medium.com/@salvatoregiordanoo/flavoring-flutter-392aaa875f36",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "education_intermediate": [
    const EntryData(
      title: "Animated Chat",
      description: "Building beautiful UIs by Google Code Labs.",
      link: "https://codelabs.developers.google.com/codelabs/flutter/#0",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Firebase Chat",
      description: "Firebase integration by Google Code Labs.",
      link: "https://codelabs.developers.google.com/codelabs/flutter-firebase/#0",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Planets-Flutter: from design to app",
      description: "Detailed planets design tutorial.",
      link: "http://sergiandreplace.com/2017/09/planets-flutter-from-design-to-app",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Todo List",
      description: "Step by step tutorial how to build Todo List with Flutter by Andrei Lesnitsky",
      link: "https://github.com/lesnitsky/todolist_flutter",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "education_beginner": [
    const EntryData(
      title: "Zero to One Animation",
      description: "Focus on animation by Mikkel Ravn.",
      link: "https://medium.com/dartlang/zero-to-one-with-flutter-part-two-5aa2f06655cb",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Animations in Flutter",
      description: "Commonly used animation examples by Muhammed Salih Güler.",
      link: "https://proandroiddev.com/animations-in-flutter-6e02ee91a0b2",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Layout Cheat Sheet",
      description: "Extensive examples of layout widgets by Tomek Polański.",
      link: "https://medium.com/flutter-community/flutter-layout-cheat-sheet-5363348d037e",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
    const EntryData(
      title: "Pooja's Guide to Flutterverse",
      description: "Step by step guide for learning Flutter for super beginners by Pooja Bhaumik.",
      link: "https://medium.com/flutter-community/i-want-to-learn-flutter-how-to-start-ffb4145f9b26",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
  "memes": [
    const EntryData(
      title: "The One",
      description: "A video about Flutter & Dart.",
      link: "https://www.youtube.com/watch?v=sIIgtClYq0s",
      createdOnMillisecondsSinceEpoch: 1573686156552,
    ),
  ],
};